#!/usr/bin/bash

/usr/lib/jvm/java-12-openjdk-amd64/bin/java -javaagent:/home/sharpvik/Dev/IntelliJ/lib/idea_rt.jar=42609:/home/sharpvik/Dev/IntelliJ/bin -Dfile.encoding=UTF-8 -classpath /home/sharpvik/Projects/java/BareBones/out/production/BareBones com.company.Main $1
